//USER

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_PROFILES = "SET_PROFILES";
export const UPDATE_PROFILES = "UPDATE_PROFILES";
